import type { PageServerLoad } from './$types';
import type { F1Data } from '$lib/types/f1.types';

export const config = {
	isr: {
		// Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
		// Setting the value to `false` means it will never expire.
		expiration: 10
	}
};

export const load = (async () => {
	const generatedAt = new Date();

	console.log('Fetching data');
	const resData: F1Data = await fetch('http://ergast.com/api/f1/current/next.json').then((res) =>
		res.json()
	);

	const f1data = resData.MRData;

	const isSprint = 'Sprint' in f1data.RaceTable.Races[0];

	return {
		generatedAt,
		f1data,
		raceData: f1data.RaceTable.Races[0],
		isSprint
	};
}) satisfies PageServerLoad;
